/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Bookmark Manager
 #	author : miyako
 #	2012/10/06
 #
 # --------------------------------------------------------------------------------*/



// --- Bookmarks
void BOOKMARK_Create(sLONG_PTR *pResult, PackagePtr pParams);
void BOOKMARK_Resolve(sLONG_PTR *pResult, PackagePtr pParams);
void BOOKMARK_Export_to_file(sLONG_PTR *pResult, PackagePtr pParams);
